### ISSUE TITLE
Any way to bake iup into the app executable?

### ISSUE THREAD

**Issue by J-Zeitler** [nim-lang/iup#5]
I'm using nim-iup in windows and when compiling there's an external dependency to `iup.dll` from my `gui.exe` file. I.e. I would need to supply both files if I were to distribute the app.

Is there some way to bake iup into my `gui.exe`-file? I guess I need to statically build/link iup. How would I do that best? (sorry, I'm a noob in these configuration management situations)

**Comment by J-Zeitler** [comment]
Turns out you have to just link everything in the world. Is this usage considered "nimonic" though or is there a better way?

```PowerShell
$ nim c -d:release --dynlibOverride:iup -L:lib/libiup.a -L:lib/libiupcd.a -L:lib/libiupim.a -L:-lgdi32 -L:-luser32 -L:-lcomdlg32 -L:-lcomctl32 -L:-lole32 -L:-luuid gui.nim
```

edit: also, `./lib/` of course contains the [_static_ version of iup](https://sourceforge.net/projects/iup/files/3.22/Windows%20Libraries/Static/) instead of the dynamic/dll version I used before

**Comment by dom96** [comment]
Looks pretty idiomatic to me. We could maybe put some of these flags into the project under a ``define``. The others require a non-universal file path I guess :\

**Comment by J-Zeitler** [comment]
Thanks for the quick answer! I'm pretty new to Nim and this was my first gui test. Discovered the `*.nim.cfg` file also. That seems like a good place to put config for longer commands.

(also, feel free to close this issue :) )

**Comment by Araq** [comment]
Yeah, sorry, your solution is the best one we have.

**Comment by ghost** [comment]
I alse have to replace `--app:gui` with `--passL:-mwindows` in static mode (the binary is 1MB size, a little big though) or gcc willl complain that 
```
iupwindows_main.o):iupwindows_main.c:(.text+0x0): multiple definition of `WinMain@16'
```

**Comment by Araq** [comment]
Compile with ``--noMain`` but don't forget to call ``NimMain`` or whatever it's called. :-)
